import ActrBindings

typealias NetworkEventHandleWrapper = ActrBindings.NetworkEventHandleWrapper
typealias NetworkAvailability = ActrBindings.NetworkAvailability
typealias NetworkTransportFlags = ActrBindings.NetworkTransportFlags
typealias NetworkSnapshot = ActrBindings.NetworkSnapshot
typealias AppLifecycleState = ActrBindings.AppLifecycleState
typealias CleanupReason = ActrBindings.CleanupReason
typealias ReconnectReason = ActrBindings.ReconnectReason
typealias NetworkEvent = ActrBindings.NetworkEvent
typealias NetworkEventResult = ActrBindings.NetworkEventResult
